COLUMN_LABELS = {
    "AGEP":     "Age",
    "SEX":      "Sex",
    "RAC1P":    "Race (recoded, detailed)",
    "HISP":     "Hispanic origin",
    "NATIVITY": "Nativity (native vs. foreign born)",
    "CIT":      "Citizenship status",
    "LANX":     "Speaks language other than English at home",
    "ENG":      "English-speaking ability",
    "MAR":      "Marital status",
    "MARHT":    "Number of times married",
    "RELSHIPP": "Relationship to reference person",
    "FER":      "Gave birth in past 12 months",
    "GCL":      "Grandparent living with grandchildren",
    "NOP":      "Number of own children (verify — see note)",
    "PAOC":     "Presence and age of own children",
    "SCHL":     "Educational attainment",
    "SCH":      "School enrollment",
    "SCHG":     "Grade level attending",
    "FOD1P":    "Field of degree (primary)",
    "MIL":      "Military service status",
    "VPS":      "Veteran period of service",
    "DIS":      "Disability (recoded)",
    "DEAR":     "Hearing difficulty",
    "DEYE":     "Vision difficulty",
    "DREM":     "Cognitive difficulty",
    "DPHY":     "Ambulatory (physical) difficulty",
    "DDRS":     "Self-care difficulty",
    "DOUT":     "Independent-living difficulty",
    "COW":      "Class of worker",
    "ESR":      "Employment status (recoded)",
    "WKHP":     "Usual hours worked per week (past 12 months)",
    "WKWN":     "Weeks worked (past 12 months)",
    "OCCP":     "Occupation",
    "INDP":     "Industry",
    "JWMNP":    "Commute time to work (minutes)",
    "JWTRNS":   "Means of transportation to work",
    "POWPUMA":  "Place of work (PUMA)",
    "WRK":      "Worked last week",
    "MIG":      "Mobility status (lived here 1 year ago)",
    "MIGSP":    "State/country of residence 1 year ago",
    "HICOV":    "Health insurance coverage (any)",
    "PRIVCOV":  "Private health insurance coverage",
    "PUBCOV":   "Public health insurance coverage",
    "WAGP":     "Wage/salary income (past 12 months)",
    "SEMP":     "Self-employment income",
    "INTP":     "Interest, dividend & rental income",
    "RETP":     "Retirement income",
    "SSP":      "Social Security income",
    "SSIP":     "Supplementary Security Income",
    "PAP":      "Public assistance income",
    "PERNP":    "Total earnings",
    "PINCP":    "Total personal income",
    "POVPIP":   "Income-to-poverty ratio",
    "ST":       "State (FIPS code)",
    "state_population": "State population",
}

VALUE_LABELS = {
    "SEX": {"1": "Male", "2": "Female"},
    "RAC1P": {
        "1": "White alone",
        "2": "Black or African American alone",
        "3": "American Indian alone",
        "4": "Alaska Native alone",
        "5": "AIAN tribes specified, or AIAN not specified and no other races",
        "6": "Asian alone",
        "7": "Native Hawaiian or Pacific Islander alone",
        "8": "Some other race alone",
        "9": "Two or more races",
    },
    "HISP": {
        "01": "Not Spanish/Hispanic/Latino",
        "02": "Mexican",
        "03": "Puerto Rican",
        "04": "Cuban",
        "05": "Dominican",
        "06": "Costa Rican",
        "07": "Guatemalan",
        "08": "Honduran",
        "09": "Nicaraguan",
        "10": "Panamanian",
        "11": "Salvadoran",
        "12": "Other Central American",
        "13": "Argentinean",
        "14": "Bolivian",
        "15": "Chilean",
        "16": "Colombian",
        "17": "Ecuadorian",
        "18": "Paraguayan",
        "19": "Peruvian",
        "20": "Uruguayan",
        "21": "Venezuelan",
        "22": "Other South American",
        "23": "Spaniard",
        "24": "All other Spanish/Hispanic/Latino",
    },
    "NATIVITY": {"1": "Native", "2": "Foreign born"},
    "CIT": {
        "1": "Born in US",
        "2": "Born in PR/US territories",
        "3": "Born abroad of US parents",
        "4": "Naturalized US citizen",
        "5": "Not a US citizen",
    },
    "LANX": {"1": "Yes", "2": "No"},
    "ENG": {
        "1": "Very well",
        "2": "Well",
        "3": "Not well",
        "4": "Not at all",
    },
    "MAR": {
        "1": "Married",
        "2": "Widowed",
        "3": "Divorced",
        "4": "Separated",
        "5": "Never married",
    },
    "MARHT": {
        "1": "One time",
        "2": "Two times",
        "3": "Three or more times",
    },
    "RELSHIPP": {
        "20": "Reference person",
        "21": "Opposite-sex husband/wife",
        "22": "Opposite-sex unmarried partner",
        "23": "Same-sex husband/wife",
        "24": "Same-sex unmarried partner",
        "25": "Biological son or daughter",
        "26": "Adopted son or daughter",
        "27": "Stepson or stepdaughter",
        "28": "Brother or sister",
        "29": "Father or mother",
        "30": "Grandchild",
        "31": "Parent-in-law",
        "32": "Son-in-law or daughter-in-law",
        "33": "Other relative",
        "34": "Roommate or housemate",
        "35": "Foster child",
        "36": "Other nonrelative",
        "37": "Institutionalized group quarters",
        "38": "Noninstitutionalized group quarters",
    },
    "FER": {"1": "Yes", "2": "No"},
    "GCL": {"1": "Yes", "2": "No"},
    "PAOC": {
        "1": "With own children under 6 only",
        "2": "With own children 6-17 only",
        "3": "With own children under 6 and 6-17",
        "4": "No own children",
    },
    "SCHL": {
        "01": "No schooling completed",
        "02": "Nursery school / preschool",
        "03": "Kindergarten",
        "04": "Grade 1",
        "05": "Grade 2",
        "06": "Grade 3",
        "07": "Grade 4",
        "08": "Grade 5",
        "09": "Grade 6",
        "10": "Grade 7",
        "11": "Grade 8",
        "12": "Grade 9",
        "13": "Grade 10",
        "14": "Grade 11",
        "15": "Grade 12, no diploma",
        "16": "Regular high school diploma",
        "17": "GED or alternative credential",
        "18": "Some college, less than 1 year",
        "19": "Some college, 1+ years, no degree",
        "20": "Associate's degree",
        "21": "Bachelor's degree",
        "22": "Master's degree",
        "23": "Professional degree beyond bachelor's",
        "24": "Doctorate degree",
    },
    "SCH": {
        "1": "Has not attended in the last 3 months",
        "2": "Public school or public college",
        "3": "Private school or private college, or home school",
    },
    "SCHG": {
        "01": "Nursery school / preschool",
        "02": "Kindergarten",
        "03": "Grade 1",
        "04": "Grade 2",
        "05": "Grade 3",
        "06": "Grade 4",
        "07": "Grade 5",
        "08": "Grade 6",
        "09": "Grade 7",
        "10": "Grade 8",
        "11": "Grade 9",
        "12": "Grade 10",
        "13": "Grade 11",
        "14": "Grade 12",
        "15": "College undergraduate years",
        "16": "Graduate or professional school",
    },
    "MIL": {
        "1": "Now on active duty",
        "2": "On active duty in the past, not now",
        "3": "Training for Reserves/National Guard only",
        "4": "Never served in the military",
    },
    "VPS": {
        "01": "Gulf War 9/2001 or later",
        "02": "Gulf War 9/2001 or later and Gulf War 8/1990-8/2001",
        "03": "Gulf War 9/2001+, Gulf War 8/1990-8/2001, and Vietnam era",
        "04": "Gulf War 8/1990-8/2001",
        "05": "Gulf War 8/1990-8/2001 and Vietnam era",
        "06": "Vietnam era",
        "07": "Vietnam era and Korean War",
        "08": "Vietnam era, Korean War, and WWII",
        "09": "Korean War",
        "10": "Korean War and WWII",
        "11": "WWII",
        "12": "Between Gulf War and Vietnam only",
        "13": "Between Vietnam and Korean War only",
        "14": "Between Korean War and WWII only",
        "15": "Pre-WWII only",
    },
    "DIS":  {"1": "With a disability", "2": "Without a disability"},
    "DEAR": {"1": "Yes", "2": "No"},
    "DEYE": {"1": "Yes", "2": "No"},
    "DREM": {"1": "Yes", "2": "No"},
    "DPHY": {"1": "Yes", "2": "No"},
    "DDRS": {"1": "Yes", "2": "No"},
    "DOUT": {"1": "Yes", "2": "No"},
    "COW": {
        "1": "Employee of a private for-profit",
        "2": "Employee of a private not-for-profit",
        "3": "Local government employee",
        "4": "State government employee",
        "5": "Federal government employee",
        "6": "Self-employed in own not incorporated business",
        "7": "Self-employed in own incorporated business",
        "8": "Working without pay in family business or farm",
        "9": "Unemployed and last worked 5+ years ago or never worked",
    },
    "ESR": {
        "1": "Civilian employed, at work",
        "2": "Civilian employed, with a job but not at work",
        "3": "Unemployed",
        "4": "Armed forces, at work",
        "5": "Armed forces, with a job but not at work",
        "6": "Not in labor force",
    },
    "JWTRNS": {
        "01": "Car, truck, or van",
        "02": "Bus",
        "03": "Subway or elevated rail",
        "04": "Long-distance train or commuter rail",
        "05": "Light rail, streetcar, or trolley",
        "06": "Ferryboat",
        "07": "Taxicab",
        "08": "Motorcycle",
        "09": "Bicycle",
        "10": "Walked",
        "11": "Worked from home",
        "12": "Other method",
    },
    "WRK": {"1": "Worked", "2": "Did not work"},
    "MIG": {
        "1": "Yes, same house (nonmovers)",
        "2": "No, outside US and PR",
        "3": "No, different house in US or PR",
    },
    "HICOV":   {"1": "With health insurance", "2": "Without health insurance"},
    "PRIVCOV": {"1": "With private health insurance", "2": "Without private health insurance"},
    "PUBCOV":  {"1": "With public health insurance",  "2": "Without public health insurance"},
    "ST": {
        "01": "Alabama",        "02": "Alaska",         "04": "Arizona",
        "05": "Arkansas",       "06": "California",     "08": "Colorado",
        "09": "Connecticut",    "10": "Delaware",       "12": "Florida",
        "13": "Georgia",        "15": "Hawaii",         "16": "Idaho",
        "17": "Illinois",       "18": "Indiana",        "19": "Iowa",
        "20": "Kansas",         "21": "Kentucky",       "22": "Louisiana",
        "23": "Maine",          "24": "Maryland",       "25": "Massachusetts",
        "26": "Michigan",       "27": "Minnesota",      "28": "Mississippi",
        "29": "Missouri",       "30": "Montana",        "31": "Nebraska",
        "32": "Nevada",         "33": "New Hampshire",  "34": "New Jersey",
        "35": "New Mexico",     "36": "New York",       "37": "North Carolina",
        "38": "North Dakota",   "39": "Ohio",           "40": "Oklahoma",
        "41": "Oregon",         "42": "Pennsylvania",   "44": "Rhode Island",
        "45": "South Carolina", "46": "South Dakota",   "47": "Tennessee",
        "48": "Texas",          "49": "Utah",           "50": "Vermont",
        "51": "Virginia",       "53": "Washington",     "54": "West Virginia",
        "55": "Wisconsin",      "56": "Wyoming",
    },
}
